destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex
title: "Maddy and Devin's Wedding Oct 2, 2011"
author:
  name: Devin Weaver
  email: "weaver.devin+wedding@gmail.com"
url: "http://maddywillyoumarryme.com"
debug: false

links:
  rsvp: "https://docs.google.com/spreadsheet/viewform?hl=en_US&formkey=dFlsWUx2clZpVlZLS09OUUFmYXdULVE6MQ#gid=0"
  registry: "http://www.amazon.com/gp/registry/wedding/2FTK3EMV9HCS3"

# features:
google:
  analytics:
    enabled: true
    id: "UA-25176709-1"
  search:
    enabled: false

disqus:
  enabled: true
