destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex
enableDisqusComments: true
topURL: "http://maddywillyoumarryme.com"
RSVPURL: "https://docs.google.com/spreadsheet/viewform?hl=en_US&formkey=dFlsWUx2clZpVlZLS09OUUFmYXdULVE6MQ#gid=0"
debug: false
